spring:
  config:
    import: application-secret.properties
  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: org.h2.Driver
    url: {DEV_DB_URL}
    username: {DEV_DB_USERNAME}
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    defer-datasource-initialization: true
  data:
    redis:
      host: {DEV_REDIS_HOST}
      port: {DEV_REDIS_PORT}

  h2:
    console:
      enabled: true
      path: {DEV_H2_CONSOLE_PATH}