spring:
  config:
    import: application-secret.properties
  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: {DEV_DB_URL}
    username: {DEV_DB_USERNAME}
    password: {DEV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  data:
    redis:
      host: {DEV_REDIS_HOST}
      port: {DEV_REDIS_PORT}