spring:
  config:
    import: application-secret.properties
  web:
    resources:
      add-mappings: false
    origin:
      server: ${SERVER_ORIGIN}

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:arabook-local-db;DATABASE_TO_UPPER=FALSE;mode=mysql
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
    header: ${JWT_ACCESS_TOKEN_HEADER}
  refresh:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}
    header: ${JWT_REFRESH_TOKEN_HEADER}