spring:
  config:
    import: application-secret.properties
  web:
    resources:
      add-mappings: false
    origin:
      server: ${SERVER_ORIGIN}

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  data:
    redis:
      host: {PROD_REDIS_HOST}
      port: {PROD_REDIS_PORT}

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
    header: ${JWT_ACCESS_TOKEN_HEADER}
  refresh:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}
    header: ${JWT_REFRESH_TOKEN_HEADER}